### ISSUE TITLE
Error formatting filesystem ext4

### ISSUE THREAD

**Issue by Ran-P** [fdupoux/fsarchiver#12] opened 2016-04-25 06:47 UTC
Trying to restore to disk archive of an ext4 partition.

$ fsarchiver archinfo /mnt/arch/data_disk.fsa 
====================== archive information ======================
Archive type:                   filesystems
Filesystems count:              1
Archive id:                     5717ccbf
Archive file format:            FsArCh_002
Archive created with:           0.6.22
Archive creation date:          2016-04-24_12-02-41
Archive label:                  <none>
Minimum fsarchiver version:     0.6.4.0
Compression level:              3 (gzip level 6)
Encryption algorithm:           none
===================== filesystem information ====================
Filesystem id in archive:       0
Filesystem format:              ext4
Filesystem label: 
Filesystem uuid:                c4a08c0a-15e9-4bdf-92fe-e2c69c482426
Original device:                /dev/sdb
Original filesystem size:       2.46 TB (2705512898560 bytes)
Space used in filesystem:       356.26 GB (382531969024 bytes)

But get an error cannot format the filesystem ext4 on partition.

$ sudo fsarchiver -v restfs /mnt/arch/data_disk.fsa id=0,dest=/dev/sdc
============= extracting filesystem 0 =============
executing [mke2fs -V]...
command [mke2fs -V] returned 0
executing [mke2fs -V]...
command [mke2fs -V] returned 0
executing [mke2fs /dev/sdc  -q  -r 1    -b 4096  -I 256  -O has_journal,ext_attr,resize_inode,dir_index,filetype
,extent,^journal_dev,flex_bg,^meta_bg,large_file,huge_file,sparse_super,uninit_bg,dir_nlink,extra_isize  -E stride=1 ]...
command [mke2fs /dev/sdc  -q  -r 1    -b 4096  -I 256  -O has_journal,ext_attr,resize_inode,dir_index,filetype,extent,^journal_dev,flex_bg,^meta_bg,large_file,huge_file,sparse_super,uninit_bg,dir_nlink,extra_isize  -E stride=1 ] returned 1
fs_ext2.c#281,extfs_mkfs(): command [mke2fs /dev/sdc  -q  -r 1    -b 4096  -I 256  -O has_journal,ext_attr,resize_inode,dir_index,filetype,extent,^journal_dev,flex_bg,^meta_bg,large_file,huge_file,sparse_super,uninit_bg,dir_nlink,extra_isize  -E stride=1 ] failed with return status=1
oper_restore.c#1281,extractar_filesystem_extract(): cannot format the filesystem ext4 on partition /dev/sdc

**Comment by marcosfrm** [comment] 2016-04-25 16:43
If you run directly

```
mke2fs /dev/sdc -q -r 1 -b 4096 -I 256 -O has_journal,ext_attr,resize_inode,dir_index,filetype,extent,^journal_dev,flex_bg,^meta_bg,large_file,huge_file,sparse_super,uninit_bg,dir_nlink,extra_isize -E stride=1
```

(be careful, `/dev/sdc` may be formated)

what does mke2fs say?

**Comment by Ran-P** [comment] 2016-04-26 07:26
Works fine

$ mke2fs /dev/sdc -q -r 1 -b 4096 -I 256 -O has_journal,ext_attr,resize_inode,dir_index,fil
etype,extent,^journal_dev,flex_bg,^meta_bg,large_file,huge_file,sparse_super,uninit_bg,dir_nlink,extra_isize -E 
stride=1
/dev/sdc is entire device, not just one partition!
Proceed anyway? (y,n) y
mke2fs: Permission denied while trying to determine filesystem size
$ sudo mke2fs /dev/sdc -q -r 1 -b 4096 -I 256 -O has_journal,ext_attr,resize_inode,dir_inde
x,filetype,extent,^journal_dev,flex_bg,^meta_bg,large_file,huge_file,sparse_super,uninit_bg,dir_nlink,extra_isiz
e -E stride=1
/dev/sdc is entire device, not just one partition!
Proceed anyway? (y,n) y
done

**Comment by Ran-P** [comment] 2016-04-26 07:37
I read somewhere that there a bug in fsarchiver when formatting ext4 filesystem. 
The ext4 command has more parameters and the buffer in the code is too small, thou the command is cut and is not valid.

**Comment by fdupoux** [comment] 2016-04-26 19:57
It should not be a problem with the buffer being too small and the command being truncated as otherwise the command would also be truncated in the error message and it is not. The buffer is actually 2048 characters long.

It sounds the problem is caused by the device not being a partition (/dev/sdc instead of /dev/sdc1) and you get an interactive prompt. As fsarchiver executes the command and does not expect interactivity it fails. Can you please re-run the command manually with an extra -F option and see if you can get it to work with no confirmation ? If it works I will add it to the fsarchiver sources.

Also you can attempt to restore this archive on a normal partition device (such as /dev/sdc1) if you have such a partition available. It would help confirm the prompt is the issue.

**Comment by Ran-P** [comment] 2016-04-27 06:44
The mke2fs with -F work without confirmation on the device. 
$ sudo mke2fs /dev/sdc -F -q -r 1 -b 4096 -I 256 -O has_journal,ext_attr,resize_inode,dir_i
ndex,filetype,extent,^journal_dev,flex_bg,^meta_bg,large_file,huge_file,sparse_super,uninit_bg,dir_nlink,extra_i
size -E stride=1
done

**Comment by fdupoux** [comment] 2016-04-27 07:13
The fix has been implemented: https://github.com/fdupoux/fsarchiver/commit/5e9a3037ace597856ed6e627565733d6f15840dd

**Closed** 2016-04-27 08:41 UTC
